config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :new, :show, :create, :destroy] do
    resources :bookmarks, only: [:index, :new, :create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to lists_path
  end

  private

  # def set_list
  #   @list = List.find(params[:id])
  # end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>
<% @bookmarks.each do |bookmark| %>
  <ul>
    <li><%= bookmark.comment %></li>
  </ul>
<% end %>

app/views/bookmarks/new.html.erb
<div class="background-new reduce-1">
  <div class="container py-5 ">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">
            <div style="responsive-1" class="header mt-3 mb-5">
                <h3 style="color: white">Add a movie to your <%= @list.name %> list</h3>
            </div>
          <%= simple_form_for [@list, @bookmark] do |f| %>
            <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
            <%= f.association :movie, prompt: 'Select a movie'%>
            <%= f.submit class: 'btn-ghost-square-blue' %>
             <%= link_to 'Back', lists_path(@list), class: "btn btn-ghost-square mb-1"  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('banner.jpg') %>);">
  <div class="container">
    <h1>Create your own WatchList!</h1>
    <p>Add as many lists and bookmarks as you want!</p>
  </div>
</div>

app/views/lists/index.html.erb
<%= render "banner" %>

<div class= "d-flex">
  <div class="container text-center">
    <header class="my-5 pb-3  ">
        <div class="header">
          <h1 style="color: white"><span data-controller="typed-js"></span></h1>
        </div>
    </header>

    <div class=" mb-5 font-work ">
    </div>
    <%# MOVIE LIST %>
    <div class="cards">
      <% @lists.each do |list| %>
        <div class="card card-category mx-4 my-5" style="width: 18rem;">
          <% if list.photo.attached? %>
              <%= cl_image_tag list.photo.key, class:"card-img-top img-thumbnail img", alt:"Card image cap", height: 300, width: 400, crop: :fill %>
          <% else %>
              <%= image_tag('istockphoto.jpg') %>
          <% end %>
          <div class="card-body pb-5 mb-3">
            <%= link_to list.name, list_path(list), class:"link" %>
          </div>
        </div>
      <% end %>
    </div>

    <%= link_to "Add a list", new_list_path, style:"font-size:1.3em; font-family: 'Cormorant SC', serif;
  ", class: " btn btn-ghost-square-big mb-5 float-center" %>

  </div>
</div>

app/views/lists/new.html.erb
<%= render "banner" %>

  <div class="container py-5 reduce">
            <div class="header mb-5 py-1">
                <h3 style="color: white">Create a New List</h3>
            </div>
          <%= simple_form_for @list do |f| %>
            <%= f.input :name, placeholder: 'Drama' %>
            <%= f.input :photo, as: :file, class: 'mb-5'%>
            <%= f.submit class: 'btn-ghost-square-blue  mt-3 '  %>
            <%= link_to 'Back', lists_path(@list), class: "btn btn-ghost-square mb-1 mx-4"  %>
          <% end %>
  </div>

app/views/lists/show.html.erb
<div class="mb-3 card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(@list.photo.key) if @list.photo.attached?%>)">
  <h1 class="title"><%= @list.name %></h1>
</div>

<div>
    <div class="d-flex responsive justify-content-end mb-5 mt-4 mx-3">
    <%= link_to 'Add a bookmark', new_list_bookmark_path(@list), class: "flex-gap btn btn-ghost-square-blue"  %>
      <%= button_to "Delete list",
                            list_path(@list),
                            method: :delete,
                            data: { confirm: "Are you sure you want to delete the '#{@list.name}' list ?" }, class: "flex-gap btn btn-ghost-square-red mx-3" %>
        <%= link_to 'Back', lists_path(@list), class: "flex-gap btn btn-ghost-square"  %>
  </div>

  <div class="container responsive mb-5 cards">
    <% @bookmarks.each do |bookmark| %>
      <div class="card  mx-5 my-3"4 style="width: 23rem;">
        <%= image_tag bookmark.movie.poster_url, class:"card-img-top rounded img-thumbnail img" %>
        <div class="card-body pb-5">
          <strong><h3 class="text-center"><%= bookmark.movie.title %></strong>
           <small><p><%= "⭐#{bookmark.movie.rating.to_i}/10" %></p></h3></small>
          <p class="text-center"><%= bookmark.movie.overview %></p>
          <div class="d-flex "><h4><em>"<%= bookmark.comment %>"</em></h4>
            <%= link_to "❌",
            bookmark_path(bookmark),
            method: :delete,
            data: { confirm: "Are you sure you want to delete '#{bookmark.movie.title}'?" },
            class:"text-end btn-x flex-grow-1 " %>
          </div>

        </div>

</div>
    <% end %>